server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/funeral_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: qianshe_password
  # redis
  redis:
    host: localhost
    port: 6379
    password: qianshe_password
    timeout: 10000
    database: 0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 微信小程序配置
wx:
  appid: your_appid
  secret: your_secret

# JWT配置
jwt:
  secret: your_jwt_secret_key_must_be_at_least_32_bytes_long
  expiration: 86400  # 24小时，单位秒 